import { defineSchema, defineTable } from "convex/server"
import { v } from "convex/values"
import { authTables } from "@convex-dev/auth/server"

const paymentStatus = v.union(v.literal("pending_review"), v.literal("confirmed"), v.literal("rejected"))

export default defineSchema({
  ...authTables,
  owners: defineTable({
    tokenIdentifier: v.string(),
    name: v.optional(v.string()),
    email: v.optional(v.string()),
    role: v.optional(v.union(v.literal("owner"), v.literal("admin"))),
    identityVerificationStatus: v.optional(v.union(v.literal("not_submitted"), v.literal("pending_review"), v.literal("verified"), v.literal("rejected"))),
    ktpStorageId: v.optional(v.id("_storage")),
    selfieStorageId: v.optional(v.id("_storage")),
    onboardingCompleted: v.optional(v.boolean()),
    createdAt: v.optional(v.number()),
  }).index("by_token_identifier", ["tokenIdentifier"]),
  properties: defineTable({
    ownerId: v.id("owners"),
    name: v.string(),
    address: v.string(),
    slug: v.string(),
    isActive: v.boolean(),
    propertyVerificationStatus: v.optional(v.union(v.literal("not_submitted"), v.literal("pending_review"), v.literal("verified"), v.literal("rejected"))),
    ownershipProofStorageId: v.optional(v.id("_storage")),
  }).index("by_owner", ["ownerId"]).index("by_slug", ["slug"]),
  subscriptions: defineTable({
    ownerId: v.id("owners"),
    tier: v.union(v.literal("free"), v.literal("starter"), v.literal("growth"), v.literal("pro")),
    billingCycle: v.union(v.literal("monthly"), v.literal("annual"), v.literal("none")),
    priceAmount: v.number(),
    status: v.union(v.literal("active"), v.literal("pending_payment"), v.literal("past_due"), v.literal("canceled")),
    currentPeriodEnd: v.optional(v.number()),
    roomCountAtLastCheck: v.number(),
    proofStorageId: v.optional(v.id("_storage")),
    reviewedByOwnerId: v.optional(v.id("owners")),
    reviewedAt: v.optional(v.number()),
    rejectionReason: v.optional(v.string()),
  }).index("by_owner", ["ownerId"]).index("by_status", ["status"]),
  property_photos: defineTable({
    propertyId: v.id("properties"),
    storageId: v.id("_storage"),
    sortOrder: v.number(),
    caption: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_property", ["propertyId"]),
  reports: defineTable({
    reporterOwnerId: v.optional(v.id("owners")),
    reporterTenantId: v.optional(v.id("tenants")),
    propertyId: v.optional(v.id("properties")),
    description: v.string(),
    status: v.union(v.literal("open"), v.literal("reviewed"), v.literal("resolved")),
    reviewedByOwnerId: v.optional(v.id("owners")),
    reviewedAt: v.optional(v.number()),
    resolutionNote: v.optional(v.string()),
  }).index("by_status", ["status"]),
  rooms: defineTable({
    propertyId: v.id("properties"),
    roomNumber: v.string(),
    status: v.union(v.literal("available"), v.literal("booked"), v.literal("occupied")),
    monthlyRent: v.number(),
    floor: v.optional(v.string()),
    roomType: v.optional(v.string()),
    sizeSqm: v.optional(v.number()),
    maxOccupants: v.optional(v.number()),
    genderCategory: v.optional(v.union(v.literal("male"), v.literal("female"), v.literal("mixed"))),
    bathroomType: v.optional(v.union(v.literal("private"), v.literal("shared"), v.literal("none"))),
    bathroomFacilities: v.optional(v.array(v.string())),
    furnitureElectronics: v.optional(v.array(v.string())),
    bedSize: v.optional(v.string()),
    annualRent: v.optional(v.number()),
    depositFee: v.optional(v.number()),
    dpAmount: v.optional(v.number()),
    dp_max_days: v.optional(v.number()),
    electricityStatus: v.optional(v.union(v.literal("included"), v.literal("metered"), v.literal("excluded"))),
    additionalFees: v.optional(v.string()),
    description: v.optional(v.string()),
  }).index("by_property", ["propertyId"]).index("by_property_and_status", ["propertyId", "status"]).index("by_property_and_room_number", ["propertyId", "roomNumber"]),
  property_facilities: defineTable({
    propertyId: v.id("properties"),
    category: v.union(v.literal("shared"), v.literal("services"), v.literal("parking"), v.literal("security"), v.literal("sports"), v.literal("other")),
    name: v.string(),
    description: v.optional(v.string()),
    isActive: v.boolean(),
    createdAt: v.number(),
  }).index("by_property", ["propertyId"]).index("by_property_and_category", ["propertyId", "category"]),
  room_media: defineTable({
    roomId: v.id("rooms"),
    kind: v.union(v.literal("photo"), v.literal("video")),
    storageId: v.id("_storage"),
    sortOrder: v.number(),
    caption: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_room", ["roomId"]).index("by_room_and_kind", ["roomId", "kind"]),
  tenants: defineTable({
    propertyId: v.id("properties"),
    roomId: v.id("rooms"),
    name: v.string(),
    phone: v.string(),
    startedAt: v.number(),
    dueDay: v.number(),
    status: v.union(v.literal("pending"), v.literal("active"), v.literal("inactive")),
    leaseDecision: v.optional(v.union(v.literal("undecided"), v.literal("continue"), v.literal("not_continuing"))),
    leaseEndsAt: v.optional(v.number()),
    // Lifecycle state machine (separate from billing status)
    payment_type: v.optional(v.union(v.literal("bulanan"), v.literal("tahunan"))),
    lifecycle_status: v.optional(v.union(v.literal("active"), v.literal("akan_pindah"), v.literal("moved_out"))),
    move_out_date: v.optional(v.number()),
    flagged_overdue_at: v.optional(v.number()),
  }).index("by_property", ["propertyId"]).index("by_room", ["roomId"]).index("by_property_and_status", ["propertyId", "status"]).index("by_status_and_due_day", ["status", "dueDay"]).index("by_lifecycle_and_move_out", ["lifecycle_status", "move_out_date"]),
  rent_charges: defineTable({
    propertyId: v.id("properties"),
    tenantId: v.id("tenants"),
    roomId: v.id("rooms"),
    period: v.string(),
    amount: v.number(),
    dueDate: v.number(),
    status: v.union(v.literal("unpaid"), v.literal("paid"), v.literal("waived")),
    paymentId: v.optional(v.id("payments")),
    createdAt: v.number(),
    paidAt: v.optional(v.number()),
  }).index("by_property_and_status", ["propertyId", "status"]).index("by_tenant_and_period", ["tenantId", "period"]).index("by_status_and_due_date", ["status", "dueDate"]),
  payments: defineTable({
    propertyId: v.id("properties"),
    tenantId: v.id("tenants"),
    roomId: v.id("rooms"),
    amount: v.number(),
    paymentType: v.optional(v.union(v.literal("dp"), v.literal("full"))),
    purpose: v.optional(v.union(v.literal("dp"), v.literal("pelunasan"), v.literal("sewa_bulanan"))),
    bookingId: v.optional(v.id("bookings")),
    paidAt: v.number(),
    dueDate: v.number(),
    billingPeriod: v.optional(v.string()),
    status: paymentStatus,
    proofStorageId: v.optional(v.id("_storage")),
    reviewerOwnerId: v.optional(v.id("owners")),
    reviewedAt: v.optional(v.number()),
    rejectionReason: v.optional(v.string()),
  }).index("by_property_and_status", ["propertyId", "status"]).index("by_tenant_and_paid_at", ["tenantId", "paidAt"]).index("by_tenant_and_due_date", ["tenantId", "dueDate"]).index("by_tenant_and_period", ["tenantId", "billingPeriod"]),
  notification_log: defineTable({
    ownerId: v.id("owners"),
    propertyId: v.optional(v.id("properties")),
    tenantId: v.optional(v.id("tenants")),
    type: v.union(
      v.literal("payment_uploaded"),
      v.literal("reminder_due"),
      v.literal("reminder_today"),
      v.literal("reminder_overdue"),
      v.literal("dp_expired"),
      v.literal("settlement_reminder"),
      v.literal("settlement_expired"),
      v.literal("overdue_flag"),
      v.literal("move_out_auto"),
      v.literal("subscription_upgrade"),
      v.literal("subscription_past_due"),
    ),
    channel: v.union(v.literal("telegram"), v.literal("whatsapp"), v.literal("both"), v.literal("log_only")),
    occurredOn: v.string(),
    status: v.union(v.literal("logged"), v.literal("skipped"), v.literal("failed")),
    payload: v.string(),
    providerEventId: v.optional(v.string()),
    externalMessageId: v.optional(v.string()),
    actionReference: v.optional(v.string()),
    errorMessage: v.optional(v.string()),
  }).index("by_tenant_and_type_and_date", ["tenantId", "type", "occurredOn"]).index("by_owner_and_type", ["ownerId", "type"]).index("by_provider_event", ["providerEventId"]),
  bot_links: defineTable({
    ownerId: v.id("owners"),
    channel: v.union(v.literal("telegram"), v.literal("whatsapp")),
    chatId: v.string(),
    status: v.union(v.literal("active"), v.literal("inactive")),
    displayName: v.optional(v.string()),
    createdAt: v.number(),
    lastSeenAt: v.optional(v.number()),
  }).index("by_owner_and_channel", ["ownerId", "channel"]).index("by_channel_and_chat_id", ["channel", "chatId"]),
  bookings: defineTable({
    propertyId: v.id("properties"),
    roomId: v.id("rooms"),
    tenantId: v.id("tenants"),
    depositAmount: v.number(),
    deadlineAt: v.number(),
    status: v.union(v.literal("pending"), v.literal("locked"), v.literal("paid_off"), v.literal("expired")),
    createdAt: v.number(),
    confirmedAt: v.optional(v.number()),
    expiredAt: v.optional(v.number()),
    // DP booking settlement flow
    dp_confirmed_at: v.optional(v.number()),
    settlement_deadline: v.optional(v.number()),
  }).index("by_property_and_status", ["propertyId", "status"]).index("by_room_and_status", ["roomId", "status"]).index("by_status_and_deadline", ["status", "deadlineAt"]).index("by_tenant", ["tenantId"]).index("by_status_and_settlement_deadline", ["status", "settlement_deadline"]),
})
