"use client"

import { useState } from "react"
import { useMutation, useQuery } from "convex/react"
import { api } from "@/convex/_generated/api"

export default function AdminVerificationPage() {
  const identity = useQuery(api.verifications.listPendingIdentity)
  const properties = useQuery(api.verifications.listPendingProperties)
  const reviewIdentity = useMutation(api.verifications.reviewIdentity)
  const reviewProperty = useMutation(api.verifications.reviewProperty)
  const [error, setError] = useState<string | null>(null)
  if (!identity || !properties) return <p className="text-sm text-[var(--ink-muted)]">Memuat verifikasi…</p>
  const review = async (kind: "identity" | "property", id: string, decision: "approved" | "rejected") => { setError(null); try { const reason = decision === "rejected" ? window.prompt("Alasan penolakan")?.trim() : undefined; if (decision === "rejected" && !reason) throw new Error("Alasan penolakan wajib diisi."); if (kind === "identity") await reviewIdentity({ ownerId: id as never, decision, reason }); else await reviewProperty({ propertyId: id as never, decision, reason }) } catch (cause) { setError(cause instanceof Error ? cause.message : "Review verifikasi gagal.") } }
  return <div><p className="text-sm text-[var(--ink-muted)]">Admin / Verifikasi</p><h1 className="mt-2 text-3xl font-semibold text-[var(--ink)]">Review verifikasi</h1>{error && <p role="alert" className="mt-4 text-sm text-[var(--warn)]">{error}</p>}<section className="mt-8"><h2 className="text-xl font-semibold text-[var(--ink)]">Identitas owner</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{identity.map(({ owner, ktpUrl, selfieUrl }) => <article key={owner._id} className="border border-[var(--line)] bg-[#fffefa] p-4"><p className="font-semibold text-[var(--ink)]">{owner.name ?? owner.email ?? "Owner"}</p><div className="mt-3 grid grid-cols-2 gap-2">{[ktpUrl, selfieUrl].map((url, index) => url ? <a href={url} target="_blank" rel="noreferrer" key={url}><img src={url} alt={index === 0 ? "KTP" : "Selfie"} className="h-36 w-full object-cover" /></a> : null)}</div><div className="mt-4 flex gap-2"><button type="button" onClick={() => void review("identity", owner._id, "approved")} className="button-primary">Approve</button><button type="button" onClick={() => void review("identity", owner._id, "rejected")} className="button-secondary">Reject</button></div></article>)}</div></section><section className="mt-10"><h2 className="text-xl font-semibold text-[var(--ink)]">Properti</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{properties.map(({ property, photos, ownershipProofUrl }) => <article key={property._id} className="border border-[var(--line)] bg-[#fffefa] p-4"><p className="font-semibold text-[var(--ink)]">{property.name}</p><div className="mt-3 grid grid-cols-3 gap-2">{photos.map((photo) => photo.url ? <img key={photo._id} src={photo.url} alt="Foto properti" className="h-24 w-full object-cover" /> : null)}</div>{ownershipProofUrl && <a href={ownershipProofUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm text-[var(--wood)] underline">Buka bukti kepemilikan</a>}<div className="mt-4 flex gap-2"><button type="button" onClick={() => void review("property", property._id, "approved")} className="button-primary">Approve</button><button type="button" onClick={() => void review("property", property._id, "rejected")} className="button-secondary">Reject</button></div></article>)}</div></section></div>
}
