"use client"

import Link from "next/link"
import { ArrowUpRight, Building2, Plus } from "lucide-react"
import { FormEvent, useState } from "react"
import { useMutation, useQuery } from "convex/react"
import { api } from "@/convex/_generated/api"

export default function PropertiesPage() {
  const [now] = useState(() => Date.now())
  const data = useQuery(api.dashboard.getOverview, { now })
  const create = useMutation(api.properties.create)
  const [showForm, setShowForm] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await create({ name: String(form.get("name") ?? ""), address: String(form.get("address") ?? ""), slug: String(form.get("slug") ?? "") }); setShowForm(false); event.currentTarget.reset() } catch (reason) { setError(reason instanceof Error ? reason.message : "Properti gagal dibuat.") } }
  if (!data) return <div className="p-8 text-sm text-[var(--ink-muted)]">Memuat properti…</div>
  return <div className="px-5 py-7 sm:px-8 sm:py-10"><div className="mx-auto max-w-7xl"><header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-[var(--ink-muted)]">Pengelolaan properti</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] text-[var(--ink)]">Properti & kamar</h1></div><button type="button" onClick={() => setShowForm((value) => !value)} className="button-primary w-fit"><Plus size={16} />Tambah properti</button></header>{showForm && <form onSubmit={submit} className="mt-7 grid gap-4 border border-[var(--line)] bg-[#fffefa] p-5 sm:grid-cols-3"><input className="field-input" name="name" required placeholder="Nama properti" /><input className="field-input" name="address" required placeholder="Alamat" /><input className="field-input" name="slug" required placeholder="slug-link" /><button className="button-primary sm:col-span-3 sm:w-fit" type="submit">Simpan properti</button>{error && <p className="text-sm text-[var(--warn)] sm:col-span-3">{error}</p>}</form>}<div className="mt-9 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{data.properties.map((property) => { const occupied = property.rooms.filter((room) => room.status === "occupied").length; const available = property.rooms.filter((room) => room.status === "available").length; return <Link key={property._id} href={`/dashboard/properties/${property._id}`} className="group border border-[var(--line)] bg-[#fffefa] p-6 transition-transform hover:-translate-y-1"><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center bg-[#8B5E34]/10 text-[var(--wood)]"><Building2 size={21} /></span><ArrowUpRight className="text-[var(--ink-muted)] transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" size={18} /></div><h2 className="mt-7 text-xl font-semibold text-[var(--ink)]">{property.name}</h2><p className="mt-2 text-sm text-[var(--ink-muted)]">{property.address}</p><p className="mt-3 break-all text-xs text-[var(--wood)]">/{property.slug}/daftar</p><div className="mt-7 grid grid-cols-3 border-t border-[var(--line)] pt-4 text-sm"><div><p className="font-mono text-lg text-[var(--ink)]">{property.rooms.length}</p><p className="text-xs text-[var(--ink-muted)]">Total kamar</p></div><div><p className="font-mono text-lg text-[var(--sage)]">{occupied}</p><p className="text-xs text-[var(--ink-muted)]">Terisi</p></div><div><p className="font-mono text-lg text-[var(--wood)]">{available}</p><p className="text-xs text-[var(--ink-muted)]">Kosong</p></div></div></Link>})}</div>{data.properties.length === 0 && <p className="mt-8 border border-dashed border-[var(--line)] p-8 text-sm text-[var(--ink-muted)]">Belum ada properti.</p>}</div></div>
}
