"use client"

import { useMemo, useState } from "react"

type AnalyticsData = { monthlyRevenue: { period: string; amount: number }[]; propertyStats: { propertyId: string; propertyName: string; occupancyRate: number; confirmedAmount: number; overdueCharges: number; activeTenants: number }[] }
const money = (value: number) => `Rp ${value.toLocaleString("id-ID")}`

export function DashboardAnalytics({ data }: { data: AnalyticsData }) {
  const [propertyId, setPropertyId] = useState("all")
  const selected = useMemo(() => propertyId === "all" ? data.propertyStats : data.propertyStats.filter((item) => item.propertyId === propertyId), [data.propertyStats, propertyId])
  const maxRevenue = Math.max(...data.monthlyRevenue.map((item) => item.amount), 1)
  return <section className="mt-12"><div className="flex flex-col justify-between gap-4 border-b border-[var(--line)] pb-4 sm:flex-row sm:items-end"><div><p className="text-sm text-[var(--ink-muted)]">Analitik operasional</p><h2 className="mt-1 text-xl font-semibold tracking-[-0.03em] text-[var(--ink)]">Performa kos</h2></div><select className="field-input max-w-xs" value={propertyId} onChange={(event) => setPropertyId(event.target.value)}><option value="all">Semua properti</option>{data.propertyStats.map((item) => <option value={item.propertyId} key={item.propertyId}>{item.propertyName}</option>)}</select></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="border border-[var(--line)] bg-[#fffefa] p-5"><p className="text-sm font-semibold text-[var(--ink)]">Pendapatan terkonfirmasi · 6 bulan</p><div className="mt-6 flex h-44 items-end gap-3">{data.monthlyRevenue.map((item) => <div className="flex min-w-0 flex-1 flex-col items-center gap-2" key={item.period}><span className="text-[10px] text-[var(--ink-muted)]">{item.amount ? money(item.amount).replace("Rp ", "") : "-"}</span><div className="w-full rounded-t bg-[var(--wood)]/75" style={{ height: `${Math.max(8, (item.amount / maxRevenue) * 115)}px` }} /><span className="text-[10px] text-[var(--ink-muted)]">{item.period.slice(5)}</span></div>)}</div></div><div className="border border-[var(--line)] bg-[#fffefa] p-5"><p className="text-sm font-semibold text-[var(--ink)]">Okupansi per properti</p><div className="mt-5 space-y-4">{selected.map((item) => <div key={item.propertyId}><div className="flex justify-between text-xs"><span className="truncate text-[var(--ink)]">{item.propertyName}</span><span className="font-mono text-[var(--wood)]">{item.occupancyRate}%</span></div><div className="mt-2 h-2 bg-[var(--background)]"><div className="h-full bg-[var(--sage)]" style={{ width: `${item.occupancyRate}%` }} /></div><p className="mt-2 text-[11px] text-[var(--ink-muted)]">{item.activeTenants} tenant aktif · {item.overdueCharges} tagihan overdue</p></div>)}{selected.length === 0 ? <p className="text-sm text-[var(--ink-muted)]">Belum ada data properti.</p> : null}</div></div></div></section>
}
