"use client"

import { useState } from "react"
import { useMutation, useQuery } from "convex/react"
import { api } from "@/convex/_generated/api"

export default function AdminBillingPage() {
  const data = useQuery(api.admin.getBillingOverview)
  const approve = useMutation(api.admin.approveSubscription)
  const reject = useMutation(api.admin.rejectSubscription)
  const [error, setError] = useState<string | null>(null)
  if (!data) return <p className="text-sm text-[var(--ink-muted)]">Memuat billing…</p>
  const decide = async (id: typeof data.pending[number]["subscription"]["_id"], action: "approve" | "reject") => { setError(null); try { if (action === "approve") await approve({ subscriptionId: id }); else { const reason = window.prompt("Alasan penolakan")?.trim(); if (!reason) throw new Error("Alasan penolakan wajib diisi."); await reject({ subscriptionId: id, reason }) } } catch (reason) { setError(reason instanceof Error ? reason.message : "Review billing gagal.") } }
  return <div><p className="text-sm text-[var(--ink-muted)]">Admin / Billing</p><h1 className="mt-2 text-3xl font-semibold text-[var(--ink)]">Review langganan</h1>{error && <p role="alert" className="mt-4 text-sm text-[var(--warn)]">{error}</p>}<section className="mt-8"><h2 className="text-xl font-semibold text-[var(--ink)]">Menunggu pembayaran</h2><div className="mt-4 space-y-3">{data.pending.length ? data.pending.map(({ subscription, owner, proofUrl }) => <article key={subscription._id} className="border border-[var(--line)] bg-[#fffefa] p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold text-[var(--ink)]">{owner?.name ?? owner?.email ?? "Owner"}</p><p className="mt-1 text-sm capitalize text-[var(--ink-muted)]">{subscription.tier} · {subscription.billingCycle} · Rp {subscription.priceAmount.toLocaleString("id-ID")}</p>{proofUrl && <a href={proofUrl} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm text-[var(--wood)] underline">Buka bukti transfer</a>}</div><div className="flex gap-2"><button type="button" onClick={() => void decide(subscription._id, "approve")} className="button-primary">Approve</button><button type="button" onClick={() => void decide(subscription._id, "reject")} className="button-secondary">Reject</button></div></div></article>) : <p className="border border-dashed border-[var(--line)] p-6 text-sm text-[var(--ink-muted)]">Tidak ada pembayaran menunggu review.</p>}</div></section><section className="mt-10"><h2 className="text-xl font-semibold text-[var(--ink)]">Past due</h2><div className="mt-4 space-y-2">{data.pastDue.length ? data.pastDue.map(({ subscription, owner }) => <div key={subscription._id} className="border border-[var(--line)] bg-[#fffefa] p-4 text-sm">{owner?.name ?? owner?.email ?? "Owner"} · <span className="capitalize">{subscription.tier}</span></div>) : <p className="border border-dashed border-[var(--line)] p-6 text-sm text-[var(--ink-muted)]">Tidak ada subscription past due.</p>}</div></section></div>
}
